/*
 * dweet.io
 * Dweet.io allows users to share data from mobile, tablets, and pcs, and them to other devices and accounts across social media platforms. Dweet.io provides an API to access the different functionality of the Dweet.io service. Users can make REST calls to read and create dweets, lock and unlock things, and perform other calls. The API returns JSON and JSONP.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AlertsApi
 */
@Ignore
public class AlertsApiTest {

    private final AlertsApi api = new AlertsApi();

    
    /**
     * Create an alert for a thing. A thing must be locked before an alert can be set.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAlertGETTest() throws ApiException {
        String who = null;
        String thing = null;
        String condition = null;
        String key = null;
        api.createAlertGET(who, thing, condition, key);

        // TODO: test validations
    }
    
    /**
     * Get the alert attached to a thing.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAlertTest() throws ApiException {
        String thing = null;
        String key = null;
        api.getAlert(thing, key);

        // TODO: test validations
    }
    
    /**
     * Remove an alert for a thing.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeAlertTest() throws ApiException {
        String thing = null;
        String key = null;
        api.removeAlert(thing, key);

        // TODO: test validations
    }
    
}
