/*
 * dweet.io
 * Dweet.io allows users to share data from mobile, tablets, and pcs, and them to other devices and accounts across social media platforms. Dweet.io provides an API to access the different functionality of the Dweet.io service. Users can make REST calls to read and create dweets, lock and unlock things, and perform other calls. The API returns JSON and JSONP.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LocksApi
 */
@Ignore
public class LocksApiTest {

    private final LocksApi api = new LocksApi();

    
    /**
     * Reserve and lock a thing.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void lockThingTest() throws ApiException {
        String thing = null;
        String lock = null;
        String key = null;
        api.lockThing(thing, lock, key);

        // TODO: test validations
    }
    
    /**
     * Remove a lock from thing.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeLockTest() throws ApiException {
        String lock = null;
        String key = null;
        api.removeLock(lock, key);

        // TODO: test validations
    }
    
    /**
     * Unlock a thing.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void unlockThingTest() throws ApiException {
        String thing = null;
        String key = null;
        api.unlockThing(thing, key);

        // TODO: test validations
    }
    
}
