openapi: 3.0.1
info:
  title: client
  version: 1.0.0
servers:
- url: http://localhost:9090/
paths:
  /dweet/for/{thingName}:
    put:
      operationId: update
      parameters:
      - name: thingName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Request'
        required: false
      responses:
        200:
          description: Successful
          content:
            application/json:
              example: Ok
  /get/latest/dweet/for/{thingName}:
    get:
      operationId: get
      parameters:
      - name: thingName
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful
          content:
            application/json:
              example: Ok
components:
  schemas:
    Request:
      type: object
