---
swagger: "2.0"
info:
  description: "Dweet.io allows users to share data from mobile, tablets, and pcs,\
    \ and them to other devices and accounts across social media platforms. Dweet.io\
    \ provides an API to access the different functionality of the Dweet.io service.\
    \ Users can make REST calls to read and create dweets, lock and unlock things,\
    \ and perform other calls. The API returns JSON and JSONP."
  version: "2.0"
  title: "dweet.io"
  x-apisguru-categories:
  - "iot"
  x-logo:
    url: "https://twitter.com/dweet_io/profile_image?size=original"
  x-origin:
  - converter:
      url: "https://github.com/lucybot/api-spec-converter"
      version: "2.7.11"
    format: "swagger"
    url: "https://dweet.io/play/definition"
    version: "1.2"
  x-providerName: "dweet.io"
host: "dweet.io"
basePath: "/"
tags:
- name: "alerts"
  description: "Alerts for things."
- name: "dweets"
  description: "Create or read dweets in short term cache."
- name: "locks"
  description: "Lock and unlock your things."
- name: "storage"
  description: "Read dweets from long term storage."
schemes:
- "https"
paths:
  /alert/{who}/when/{thing}/{condition}:
    get:
      tags:
      - "alerts"
      summary: "Create an alert for a thing. A thing must be locked before an alert\
        \ can be set."
      operationId: "createAlertGET"
      parameters:
      - name: "who"
        in: "path"
        description: "A comma separated list of Email addresses to send the alert\
          \ to."
        required: true
        type: "string"
      - name: "thing"
        in: "path"
        description: "A unique name of a thing. It is recommended that you use a GUID\
          \ as to avoid name collisions."
        required: true
        type: "string"
      - name: "condition"
        in: "path"
        description: "A condition that returns a string or a true value if a condition\
          \ is met."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid key for a locked thing. If the thing is not locked,\
          \ this can be ignored."
        required: true
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /dweet/for/{thing}:
    post:
      tags:
      - "dweets"
      summary: "Create a dweet for a thing."
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing. It is recommended that you use a GUID\
          \ as to avoid name collisions."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid key for a locked thing. If the thing is not locked,\
          \ this can be ignored."
        required: false
        type: "string"
      - in: "body"
        name: "content"
        description: "The actual content of the string. Can be any valid JSON string."
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "No response was specified"
  /dweet/quietly/for/{thing}:
    post:
      tags:
      - "dweets"
      summary: "Create a dweet for a thing.  This method differs from /dweet/for/{thing}\
        \ only in that successful dweets result in an HTTP 204 response rather than\
        \ the typical verbose response."
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing. It is recommended that you use a GUID\
          \ as to avoid name collisions."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid key for a locked thing. If the thing is not locked,\
          \ this can be ignored."
        required: false
        type: "string"
      - in: "body"
        name: "content"
        description: "The actual content of the string. Can be any valid JSON string."
        required: true
        schema:
          type: "string"
      responses:
        200:
          description: "No response was specified"
  /get/alert/for/{thing}:
    get:
      tags:
      - "alerts"
      summary: "Get the alert attached to a thing."
      operationId: "getAlert"
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid key for a locked thing. If the thing is not locked,\
          \ this can be ignored."
        required: true
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /get/dweets/for/{thing}:
    get:
      tags:
      - "dweets"
      summary: "Read the last 5 cached dweets for a thing."
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid key for a locked thing. If the thing is not locked,\
          \ this can be ignored."
        required: false
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /get/latest/dweet/for/{thing}:
    get:
      tags:
      - "dweets"
      summary: "Read the latest dweet for a thing."
      operationId: "getLatestDweet"
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid key for a locked thing. If the thing is not locked,\
          \ this can be ignored."
        required: false
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /get/stored/alerts/for/{thing}:
    get:
      tags:
      - "storage"
      summary: "Read all the saved alerts for a thing from long term storage.  You\
        \ can query a maximum of 1 day per request and a granularly of 1 hour."
      operationId: "getStoredAlerts"
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid key for a locked thing. If the thing is not locked,\
          \ this can be ignored."
        required: true
        type: "string"
      - name: "date"
        in: "query"
        description: "The calendar date (YYYY-MM-DD) from which you'd like to start\
          \ your query.  The response will be a maximum of one day."
        required: true
        type: "string"
      - name: "hour"
        in: "query"
        description: "The hour of the day represented in the date parameter in 24-hour\
          \ (00-23) format.  If this parameter is included, a maximum of 1 hour will\
          \ be returned starting at this hour."
        required: false
        type: "string"
      - name: "responseType"
        in: "query"
        description: "Current valid parameters for this are 'csv' and 'json'.  If\
          \ this parameter is left blank, all responses default to hapi-json dweet-speak."
        required: false
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /get/stored/dweets/for/{thing}:
    get:
      tags:
      - "storage"
      summary: "Read all the saved dweets for a thing from long term storage.  You\
        \ can query a maximum of 1 day per request and a granularly of 1 hour."
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid key for a locked thing. If the thing is not locked,\
          \ this can be ignored."
        required: true
        type: "string"
      - name: "date"
        in: "query"
        description: "The calendar date (YYYY-MM-DD) from which you'd like to start\
          \ your query.  The response will be a maximum of one day."
        required: true
        type: "string"
      - name: "hour"
        in: "query"
        description: "The hour of the day represented in the date parameter in 24-hour\
          \ (00-23) format.  If this parameter is included, a maximum of 1 hour will\
          \ be returned starting at this hour."
        required: false
        type: "string"
      - name: "responseType"
        in: "query"
        description: "Current valid parameters for this are 'csv' and 'json'.  If\
          \ this parameter is left blank, all responses default to hapi-json dweet-speak."
        required: false
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /listen/for/dweets/from/{thing}:
    get:
      tags:
      - "dweets"
      summary: "Listen for dweets from a thing."
      description: "Sorry, this function uses HTTP chunked responses and cannot be\
        \ tested here. Try something like: <pre>curl --raw https://dweet.io/listen/for/dweets/from/{thing}</pre>"
      operationId: "listenForDweets"
      parameters:
      - name: "thing"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /lock/{thing}:
    get:
      tags:
      - "locks"
      summary: "Reserve and lock a thing."
      operationId: "lockThing"
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing."
        required: true
        type: "string"
      - name: "lock"
        in: "query"
        description: "A valid dweet.io lock."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid dweet.io master key."
        required: true
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /remove/alert/for/{thing}:
    get:
      tags:
      - "alerts"
      summary: "Remove an alert for a thing."
      operationId: "removeAlert"
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid key for a locked thing. If the thing is not locked,\
          \ this can be ignored."
        required: true
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /remove/lock/{lock}:
    get:
      tags:
      - "locks"
      summary: "Remove a lock from thing."
      operationId: "removeLock"
      parameters:
      - name: "lock"
        in: "path"
        description: "A valid dweet.io lock."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid dweet.io master key."
        required: true
        type: "string"
      responses:
        200:
          description: "No response was specified"
  /unlock/{thing}:
    get:
      tags:
      - "locks"
      summary: "Unlock a thing."
      operationId: "unlockThing"
      parameters:
      - name: "thing"
        in: "path"
        description: "A unique name of a thing."
        required: true
        type: "string"
      - name: "key"
        in: "query"
        description: "A valid dweet.io master key."
        required: true
        type: "string"
      responses:
        200:
          description: "No response was specified"
definitions: {}
